[package]
name = "day1"
version = "0.1.0"
authors = ["ClÃ©ment Sibille <claymeuns@protonmail.com>"]
edition = "2018"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part1-naive"
path = "src/part1-naive.rs"


