[package]
name = "day6"
version = "0.1.0"
authors = ["ClÃ©ment Sibille <claymeuns@protonmail.com>"]
edition = "2018"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[dependencies]
itertools = "^0.9.0"